# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opsmatesdk
from opsmatesdk.models.health import Health  # noqa: E501
from opsmatesdk.rest import ApiException


class TestHealth(unittest.TestCase):
    """Health unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealth(self):
        """Test Health"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsmatesdk.models.health.Health()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
