# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opsmatesdk
from opsmatesdk.api.default_api import DefaultApi  # noqa: E501
from opsmatesdk.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_api_v1_health_get(self):
        """Test case for health_api_v1_health_get

        Health  # noqa: E501
        """
        pass

    def test_models_api_v1_models_get(self):
        """Test case for models_api_v1_models_get

        Models  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
